### PR TITLE
[Reviewer: AMC] Remove some packages that are no longer used

### PR DESCRIPTION
**Pull request by AlexHockey**
Does what it says on the tin.

### CODE REVIEW

**Comment by bossmc** [comment]
Does `clearwater-snmpd` get installed through some other means?  Otherwise I don't think SNMP stats will work.

**Comment by johadalin** [comment]
@AlexHockey I've just noticed that we still have these way outdated packages still up on the repo server, and @eleanor-merry pointed me to this PR. 
Before i start tinkering in chef would you be able to merge this in?

**Comment by AlexHockey** [comment]
I'd forgotten all about this. Andy pointed out that `clearwater-snmpd` needs to get installed some other way. I didn't get round to implementing that and I don't have time to right now. Feel free to pick this issue up if its blocking you.

**Comment by eleanor-merry** [comment]
:shipit:

**Pull request merged**
