### PR TITLE
Allow Chef to setup new SAS configuration

### PR DESCRIPTION
**Pull request by ChrisRees**
Make Chef configure SAS using the new sas.json config file rather than the option in shared_config.

### CODE REVIEW

**Comment by ChrisRees** [comment]
Adam, here is the PR we've discussed.
The main thing I'm worried about here is the IPSocket.getaddress()
It seems to be the recommended way of getting an address from a hostname (as we require an IP), but I'm struggling to find what will happen if it's passed an IP Address.

Do you have any opinions on a better way of doing this?

**Comment by johadalin** [comment]
This looks fairly reasonable. I just tested the IPSocket stuff, and it looks like it handles IPs as strings at least:
```
require 'socket'

ip = IPSocket.getaddress("localhost")
ip2 = IPSocket.getaddress("127.0.0.1")

puts("ip1")
puts(ip)
puts("ip2")
puts(ip2)
```
Gives
```
require 'socket'

ip = IPSocket.getaddress("localhost")
ip2 = IPSocket.getaddress("127.0.0.1")

puts("ip1")
puts(ip)
puts("ip2")
puts(ip2)```

As discussed, it's going to be harder to test before the other changes are merged down, but i'm kicking off a deployment on my dev setup to see if it gets as far as downloading at least. I'll let you know if it gets there.

**Comment by johadalin** [comment]
Sadly, on running it all, it didn't crash and burn. I don't believe it tried running your steps. the relevant output seems to be 
```
54.234.218.114 Recipe: clearwater::shared_config
54.234.218.114
54.234.218.114   * package[clearwater-management] action install
54.234.218.114  (up to date)
54.234.218.114
54.234.218.114   * ruby_block[wait_for_etcd] action run
54.234.218.114
54.234.218.114
54.234.218.114     - execute the ruby block wait_for_etcd
54.234.218.114
54.234.218.114
54.234.218.114
54.234.218.114   * execute[poll_etcd] action run
54.234.218.114
54.234.218.114
54.234.218.114     - execute /usr/share/clearwater/bin/poll_etcd.sh --quorum
54.234.218.114
54.234.218.114
54.234.218.114
54.234.218.114   * execute[download_shared_config] action run
54.234.218.114
54.234.218.114
54.234.218.114     - execute /usr/share/clearwater/clearwater-config-manager/scripts/cw-config download shared_config --autoconfirm
54.234.218.114
54.234.218.114
54.234.218.114
54.234.218.114   * execute[poll_etcd] action run
54.234.218.114
54.234.218.114
54.234.218.114     - execute /usr/share/clearwater/bin/poll_etcd.sh --quorum
54.234.218.114
54.234.218.114
54.234.218.114
54.234.218.114   * execute[download_shared_config] action run
54.234.218.114
54.234.218.114
54.234.218.114     - execute /usr/share/clearwater/clearwater-config-manager/scripts/cw-config download shared_config --autoconfirm
54.234.218.114
54.234.218.114
54.234.218.114
54.234.218.114   * template[/home/ubuntu/clearwater-config-manager/root/shared_config] action create
54.234.218.114  (up to date)
54.234.218.114
54.234.218.114   * execute[upload_shared_config] action nothing
54.234.218.114  (up to date)
54.234.218.114
54.234.218.114 Chef Client finished, 6 resources updated
54.234.218.114
```

**Comment by johadalin** [comment]
Just found my metadata was set wrong. probably just uploaded that to master 0.1.0. Retrying on the right metadata version...

**Comment by johadalin** [comment]
yep. That was it. It now crashes wonderfully:
```
54.152.106.245   * execute[download_sas_config] action run
54.152.106.245
54.152.106.245
54.152.106.245 ================================================================================
54.152.106.245
54.152.106.245 Error executing action `run` on resource 'execute[download_sas_config]'
54.152.106.245
54.152.106.245 ================================================================================
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245 Mixlib::ShellOut::ShellCommandFailed
54.152.106.245
54.152.106.245 ------------------------------------
54.152.106.245
54.152.106.245 Expected process to exit with [0], but received '2'
54.152.106.245
54.152.106.245 ---- Begin output of /usr/share/clearwater/clearwater-config-manager/scripts/cw-config download sas.json --autoconfirm ----
54.152.106.245
54.152.106.245 STDOUT:
54.152.106.245
54.152.106.245 STDERR: usage: cw-config [-h] [--autoconfirm] [--force] [--log-level LOG_LEVEL]
54.152.106.245
54.152.106.245                  action config_type
54.152.106.245
54.152.106.245 cw-config: error: argument config_type: invalid choice: sas.json (choose from shared_config, dns_json).
54.152.106.245
54.152.106.245 However some configuration is only available on a specific node type.
54.152.106.245
54.152.106.245 Check that you are using the correct node type for the
54.152.106.245
54.152.106.245 configuration type you are trying to modify.
54.152.106.245
54.152.106.245 ---- End output of /usr/share/clearwater/clearwater-config-manager/scripts/cw-config download sas.json --autoconfirm ----
54.152.106.245
54.152.106.245 Ran /usr/share/clearwater/clearwater-config-manager/scripts/cw-config download sas.json --autoconfirm returned 2
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245 Resource Declaration:
54.152.106.245
54.152.106.245 ---------------------
54.152.106.245
54.152.106.245 # In /var/chef/cache/cookbooks/clearwater/recipes/shared_config.rb
54.152.106.245
54.152.106.245
54.152.106.245 137: execute "download_sas_config" do
54.152.106.245
54.152.106.245 138:   user "ubuntu"
54.152.106.245
54.152.106.245 139:   command "/usr/share/clearwater/clearwater-config-manager/scripts/cw-config download sas.json --autoconfirm"
54.152.106.245
54.152.106.245 140:   action :run
54.152.106.245
54.152.106.245 141: end
54.152.106.245
54.152.106.245 142:
54.152.106.245
54.152.106.245 143: sas_ip = IPSocket.getaddress(node[:clearwater][:sas_server])
54.152.106.245
54.152.106.245 144:
54.152.106.245
54.152.106.245 145: template "/home/ubuntu/clearwater-config-manager/root/sas.json" do
54.152.106.245
54.152.106.245 146:   mode "0644"
54.152.106.245
54.152.106.245 147:   source "sas.json.erb"
54.152.106.245
54.152.106.245 148:   variables sas_ip: sas_ip
54.152.106.245
54.152.106.245 149:   notifies :run, "execute[upload_sas_config]", :immediately
54.152.106.245
54.152.106.245 150: end
54.152.106.245
54.152.106.245 151:
54.152.106.245
54.152.106.245 152: execute "upload_sas_config" do
54.152.106.245
54.152.106.245 153:   user "ubuntu"
54.152.106.245
54.152.106.245 154:   command "/usr/share/clearwater/clearwater-config-manager/scripts/cw-config upload sas.json --autoconfirm"
54.152.106.245
54.152.106.245 155:   action :nothing
54.152.106.245
54.152.106.245 156: end
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245 Compiled Resource:
54.152.106.245
54.152.106.245 ------------------
54.152.106.245
54.152.106.245 # Declared in /var/chef/cache/cookbooks/clearwater/recipes/shared_config.rb:137:in `from_file'
54.152.106.245
54.152.106.245
54.152.106.245 execute("download_sas_config") do
54.152.106.245
54.152.106.245   action [:run]
54.152.106.245
54.152.106.245   retries 0
54.152.106.245
54.152.106.245   retry_delay 2
54.152.106.245
54.152.106.245   command "/usr/share/clearwater/clearwater-config-manager/scripts/cw-config download sas.json --autoconfirm"
54.152.106.245
54.152.106.245   backup 5
54.152.106.245
54.152.106.245   returns 0
54.152.106.245
54.152.106.245   user "ubuntu"
54.152.106.245
54.152.106.245   cookbook_name "clearwater"
54.152.106.245
54.152.106.245   recipe_name "shared_config"
54.152.106.245
54.152.106.245 end
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245
54.152.106.245 [2018-03-07T18:34:00+00:00] ERROR: Running exception handlers
54.152.106.245
54.152.106.245 [2018-03-07T18:34:00+00:00] FATAL: Saving node information to /var/chef/cache/failed-run-data.json
54.152.106.245
54.152.106.245 [2018-03-07T18:34:00+00:00] ERROR: Exception handlers complete
54.152.106.245
54.152.106.245 Chef Client failed. 8 resources updated
54.152.106.245
54.152.106.245 [2018-03-07T18:34:00+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
54.152.106.245
54.152.106.245 [2018-03-07T18:34:00+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[download_sas_config] (clearwater::shared_config line 137) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'
54.152.106.245
54.152.106.245 ---- Begin output of /usr/share/clearwater/clearwater-config-manager/scripts/cw-config download sas.json --autoconfirm ----
54.152.106.245
54.152.106.245 STDOUT:
54.152.106.245
54.152.106.245 STDERR: usage: cw-config [-h] [--autoconfirm] [--force] [--log-level LOG_LEVEL]
54.152.106.245
54.152.106.245                  action config_type
54.152.106.245
54.152.106.245 cw-config: error: argument config_type: invalid choice: sas.json (choose from shared_config, dns_json).
54.152.106.245
54.152.106.245 However some configuration is only available on a specific node type.
54.152.106.245
54.152.106.245 Check that you are using the correct node type for the
54.152.106.245
54.152.106.245 configuration type you are trying to modify.
54.152.106.245
54.152.106.245 ---- End output of /usr/share/clearwater/clearwater-config-manager/scripts/cw-config download sas.json --autoconfirm ----
54.152.106.245
54.152.106.245 Ran /usr/share/clearwater/clearwater-config-manager/scripts/cw-config download sas.json --autoconfirm returned 2
```

**Comment by johadalin** [comment]
I can't see any problems in the code changes, and given it does appear to try to run, it's probably going to work mostly as expected. 
If you have a bunch of install packages built somewhere i could try a deployment with them and see if it works. Presumably it'd actually just eb the config manager package or something? 
Can chat about it in the morning

**Comment by johadalin** [comment]
@jack-atack Have you done a test to see if this works yet? And if so have you uploaded the changes to the master cookbook? (metadate 0.1.0)

**Pull request merged**
